# include path for /tools folder
import sys
import os.path
tool_dir = (os.path.abspath(
            os.path.join(os.path.dirname(__file__), '..', '..')) + '/tools/')
sys.path.append(tool_dir)


from ADB_Action_Scipt import ActionScript
from RC_Code import SonyRCKey
from AppList import AppList

# create an instance of the class, variables can be change
tv = ActionScript()
rc = SonyRCKey()
app = AppList()

# Print Requirements
print("This script is for checking Parental Locks on channels with specifiic ratings:")
print("Navigate to settings -> Parental Lock and choose settings")
print("Please verify the ratings etc as channel changes according to the settings\n\n")

start = input("Press Enter when ready to start the script")
# Automation Start
#Tunes to channels input
tv.press_rc_key(rc.CHANNELS)

tv.wait_in_second(1.25)
tv.press_rc_key(rc.DISPLAY)
tv.wait_in_second(0.75)
tv.press_rc_key(rc.DISPLAY)
tv.wait_in_second(1.5)
print("check for the TV rating\n")

tv.press_rc_key(rc.CHANNEL_UP)
tv.wait_in_second(1.25)
tv.press_rc_key(rc.DISPLAY)
tv.wait_in_second(0.75)
tv.press_rc_key(rc.DISPLAY)
tv.wait_in_second(1.5)
print("check for the TV rating\n")

tv.press_rc_key(rc.CHANNEL_UP)
tv.wait_in_second(1.25)
tv.press_rc_key(rc.DISPLAY)
tv.wait_in_second(0.75)
tv.press_rc_key(rc.DISPLAY)
tv.wait_in_second(1.5)
print("check for the TV rating\n")

tv.press_rc_key(rc.CHANNEL_UP)
tv.wait_in_second(1.25)
tv.press_rc_key(rc.DISPLAY)
tv.wait_in_second(0.75)
tv.press_rc_key(rc.DISPLAY)
tv.wait_in_second(1.5)
print("check for the TV rating\n")

tv.press_rc_key(rc.CHANNEL_UP)
tv.wait_in_second(1.25)
tv.press_rc_key(rc.DISPLAY)
tv.wait_in_second(0.75)
tv.press_rc_key(rc.DISPLAY)
tv.wait_in_second(1.5)
print("check for the TV rating\n")

tv.press_rc_key(rc.CHANNEL_UP)
tv.wait_in_second(1.25)
tv.press_rc_key(rc.DISPLAY)
tv.wait_in_second(0.75)
tv.press_rc_key(rc.DISPLAY)
tv.wait_in_second(1.5)
print("check for the TV rating\n")

tv.press_rc_key(rc.CHANNEL_UP)
tv.wait_in_second(1.25)
tv.press_rc_key(rc.DISPLAY)
tv.wait_in_second(0.75)
tv.press_rc_key(rc.DISPLAY)
tv.wait_in_second(1.5)
print("check for the TV rating\n")

tv.press_rc_key(rc.CHANNEL_UP)
tv.wait_in_second(1.25)
tv.press_rc_key(rc.DISPLAY)
tv.wait_in_second(0.75)
tv.press_rc_key(rc.DISPLAY)
tv.wait_in_second(1.5)
print("check for the TV rating\n")

tv.press_rc_key(rc.CHANNEL_UP)
tv.wait_in_second(1.25)
tv.press_rc_key(rc.DISPLAY)
tv.wait_in_second(0.75)
tv.press_rc_key(rc.DISPLAY)
tv.wait_in_second(1.5)
print("check for the TV rating\n")

tv.press_rc_key(rc.CHANNEL_UP)
tv.wait_in_second(1.25)
tv.press_rc_key(rc.DISPLAY)
tv.wait_in_second(0.75)
tv.press_rc_key(rc.DISPLAY)
tv.wait_in_second(1.5)
print("check for the TV rating\n")

tv.press_rc_key(rc.CHANNEL_UP)
tv.wait_in_second(1.25)
tv.press_rc_key(rc.DISPLAY)
tv.wait_in_second(0.75)
tv.press_rc_key(rc.DISPLAY)
tv.wait_in_second(1.5)
print("check for the TV rating\n")

tv.press_rc_key(rc.CHANNEL_UP)
tv.wait_in_second(1.25)
tv.press_rc_key(rc.DISPLAY)
tv.wait_in_second(0.75)
tv.press_rc_key(rc.DISPLAY)
tv.wait_in_second(1.5)
print("check for the TV rating\n")

tv.press_rc_key(rc.CHANNEL_UP)
tv.wait_in_second(1.25)
tv.press_rc_key(rc.DISPLAY)
tv.wait_in_second(0.75)
tv.press_rc_key(rc.DISPLAY)
tv.wait_in_second(1.5)
print("check for the TV rating\n")

tv.press_rc_key(rc.CHANNEL_UP)
tv.wait_in_second(1.25)
tv.press_rc_key(rc.DISPLAY)
tv.wait_in_second(0.75)
tv.press_rc_key(rc.DISPLAY)
tv.wait_in_second(1.5)
print("check for the TV rating\n")

tv.press_rc_key(rc.CHANNEL_UP)
tv.wait_in_second(1.25)
tv.press_rc_key(rc.DISPLAY)
tv.wait_in_second(0.75)
tv.press_rc_key(rc.DISPLAY)
tv.wait_in_second(1.5)
print("check for the TV rating\n")

tv.press_rc_key(rc.CHANNEL_UP)
tv.wait_in_second(1.25)
tv.press_rc_key(rc.DISPLAY)
tv.wait_in_second(0.75)
tv.press_rc_key(rc.DISPLAY)
tv.wait_in_second(1.5)
print("check for the TV rating\n")

tv.press_rc_key(rc.CHANNEL_UP)
tv.wait_in_second(1.25)
tv.press_rc_key(rc.DISPLAY)
tv.wait_in_second(0.75)
tv.press_rc_key(rc.DISPLAY)
tv.wait_in_second(1.5)
print("check for the TV rating\n")

tv.press_rc_key(rc.CHANNEL_UP)
tv.wait_in_second(1.25)
tv.press_rc_key(rc.DISPLAY)
tv.wait_in_second(0.75)
tv.press_rc_key(rc.DISPLAY)
tv.wait_in_second(1.5)
print("check for the TV rating\n")

tv.press_rc_key(rc.CHANNEL_UP)
tv.wait_in_second(1.25)
tv.press_rc_key(rc.DISPLAY)
tv.wait_in_second(0.75)
tv.press_rc_key(rc.DISPLAY)
tv.wait_in_second(1.5)
print("check for the TV rating\n")

tv.press_rc_key(rc.CHANNEL_UP)
tv.wait_in_second(1.25)
tv.press_rc_key(rc.DISPLAY)
tv.wait_in_second(0.75)
tv.press_rc_key(rc.DISPLAY)
tv.wait_in_second(1.5)
print("check for the TV rating\n")

tv.press_rc_key(rc.CHANNEL_UP)
tv.wait_in_second(1.25)
tv.press_rc_key(rc.DISPLAY)
tv.wait_in_second(0.75)
tv.press_rc_key(rc.DISPLAY)
tv.wait_in_second(1.5)
print("check for the TV rating\n")

tv.press_rc_key(rc.CHANNEL_UP)
tv.wait_in_second(1.25)
tv.press_rc_key(rc.DISPLAY)
tv.wait_in_second(0.75)
tv.press_rc_key(rc.DISPLAY)
tv.wait_in_second(1.5)
print("check for the TV rating\n")

tv.press_rc_key(rc.CHANNEL_UP)
tv.wait_in_second(1.25)
tv.press_rc_key(rc.DISPLAY)
tv.wait_in_second(0.75)
tv.press_rc_key(rc.DISPLAY)
tv.wait_in_second(1.5)
print("check for the TV rating\n")

tv.press_rc_key(rc.CHANNEL_UP)
tv.wait_in_second(1.25)
tv.press_rc_key(rc.DISPLAY)
tv.wait_in_second(0.75)
tv.press_rc_key(rc.DISPLAY)
tv.wait_in_second(1.5)
print("check for the TV rating\n")

tv.press_rc_key(rc.CHANNEL_UP)
tv.wait_in_second(1.25)
tv.press_rc_key(rc.DISPLAY)
tv.wait_in_second(0.75)
tv.press_rc_key(rc.DISPLAY)
tv.wait_in_second(1.5)
print("check for the TV rating\n")

tv.press_rc_key(rc.CHANNEL_UP)
tv.wait_in_second(1.25)
tv.press_rc_key(rc.DISPLAY)
tv.wait_in_second(0.75)
tv.press_rc_key(rc.DISPLAY)
tv.wait_in_second(1.5)
print("check for the TV rating\n")

tv.press_rc_key(rc.CHANNEL_UP)
tv.wait_in_second(1.25)
tv.press_rc_key(rc.DISPLAY)
tv.wait_in_second(0.75)
tv.press_rc_key(rc.DISPLAY)
tv.wait_in_second(1.5)
print("check for the TV rating\n")

tv.press_rc_key(rc.CHANNEL_UP)
tv.wait_in_second(1.25)
tv.press_rc_key(rc.DISPLAY)
tv.wait_in_second(0.75)
tv.press_rc_key(rc.DISPLAY)
tv.wait_in_second(1.5)
print("check for the TV rating\n")

tv.press_rc_key(rc.CHANNEL_UP)
tv.wait_in_second(1.25)
tv.press_rc_key(rc.DISPLAY)
tv.wait_in_second(0.75)
tv.press_rc_key(rc.DISPLAY)
tv.wait_in_second(1.5)
print("check for the TV rating\n")

tv.press_rc_key(rc.CHANNEL_UP)
tv.wait_in_second(1.25)
tv.press_rc_key(rc.DISPLAY)
tv.wait_in_second(0.75)
tv.press_rc_key(rc.DISPLAY)
tv.wait_in_second(1.5)
print("check for the TV rating\n")

tv.press_rc_key(rc.CHANNEL_UP)
tv.wait_in_second(1.25)
tv.press_rc_key(rc.DISPLAY)
tv.wait_in_second(0.75)
tv.press_rc_key(rc.DISPLAY)
tv.wait_in_second(1.5)
print("check for the TV rating\n")

tv.press_rc_key(rc.CHANNEL_UP)
tv.wait_in_second(1.25)
tv.press_rc_key(rc.DISPLAY)
tv.wait_in_second(0.75)
tv.press_rc_key(rc.DISPLAY)
tv.wait_in_second(1.5)
print("check for the TV rating\n")

tv.press_rc_key(rc.CHANNEL_UP)
tv.wait_in_second(1.25)
tv.press_rc_key(rc.DISPLAY)
tv.wait_in_second(0.75)
tv.press_rc_key(rc.DISPLAY)
tv.wait_in_second(1.5)
print("check for the TV rating\n")

tv.press_rc_key(rc.CHANNEL_UP)
tv.wait_in_second(1.25)
tv.press_rc_key(rc.DISPLAY)
tv.wait_in_second(0.75)
tv.press_rc_key(rc.DISPLAY)
tv.wait_in_second(1.5)
print("check for the TV rating\n")

finish = input("Press enter to power off TV or exit script")
print("RC OFF TV")
tv.press_rc_key(rc.POWER)

# ------------------------------- Keep terminal open ---------------------------------
close = input("Press Enter to close terminal")