class SonyRCKey:
    """A list of remote control key codes for Sony TV"""

    def __init__(self):
        """initialize key codes"""
        self.POWER = 'KEYCODE_POWER'
        self.INPUT = "KEYCODE_TV_INPUT"
        self.BRAIVA_SYNC_MENU = "KEYCODE_BUTTON_3"
        self.STB_MENU = "KEYCODE_BUTTON_10"

        self.NUMBER_0 = "KEYCODE_0"
        self.NUMBER_1 = "KEYCODE_1"
        self.NUMBER_2 = "KEYCODE_2"
        self.NUMBER_3 = "KEYCODE_3"
        self.NUMBER_4 = "KEYCODE_4"
        self.NUMBER_5 = "KEYCODE_5"
        self.NUMBER_6 = "KEYCODE_6"
        self.NUMBER_7 = "KEYCODE_7"
        self.NUMBER_8 = "KEYCODE_8"
        self.NUMBER_9 = "KEYCODE_9"
        self.DOT = "KEYCODE_PERIOD"
        self.DISPLAY = "KEYCODE_INFO"

        self.GOOGLE_PLAY = "KEYCODE_BUTTON_8"
        self.NETFLIX = "KEYCODE_BUTTON_4"
        self.YOUTUBE = "KEYCODE_BUTTON_9"
        self.YELLOW = "KEYCODE_PROG_YELLOW"
        self.BLUE = "KEYCODE_PROG_BLUE"
        self.RED = "KEYCODE_PROG_RED"
        self.GREEN = "KEYCODE_PROG_GREEN"

        self.ACTION_MENU = "KEYCODE_BUTTON_2"
        self.GUIDE = "KEYCODE_GUIDE"
        self.APPS = "KEYCODE_ALL_APPS"
        self.BACK = "KEYCODE_BACK"
        self.HOME = "KEYCODE_HOME"
        self.TV = "KEYCODE_TV"
        self.DISCOVER = "KEYCODE_BUTTON_1"

        self.UP = "KEYCODE_DPAD_UP"
        self.DOWN = "KEYCODE_DPAD_DOWN"
        self.LEFT = "KEYCODE_DPAD_LEFT"
        self.RIGHT = "KEYCODE_DPAD_RIGHT"
        self.ENTER = "KEYCODE_DPAD_CENTER"

        self.VOLUME_UP = "KEYCODE_VOLUME_UP"
        self.VOLUME_DOWN = "KEYCODE_VOLUME_DOWN"
        self.JUMP = "KEYCODE_LAST_CHANNEL"
        self.MUTE = "KEYCODE_VOLUME_MUTE"
        self.CHANNEL_UP = "KEYCODE_CHANNEL_UP"
        self.CHANNEL_DOWN = "KEYCODE_CHANNEL_DOWN"

        self.AUDIO = "KEYCODE_MEDIA_AUDIO_TRACK"
        self.FF = "KEYCODE_MEDIA_FAST_FORWARD"
        self.PLAY = "KEYCODE_MEDIA_PLAY"
        self.RW = "KEYCODE_MEDIA_REWIND"
        self.SUBTITLE = "KEYCODE_CAPTIONS"
        self.PREV = "KEYCODE_MEDIA_PREVIOUS"
        self.PAUSE = "KEYCODE_MEDIA_PLAY_PAUSE"
        self.NEXT = "KEYCODE_MEDIA_NEXT"
        self.HELP = "KEYCODE_HELP"
        self.WIDE = "KEYCODE_TV_ZOOM_MODE"
        self.STOP = "KEYCODE_MEDIA_STOP"

        # Special keys
        self.HDMI1 = "KEYCODE_TV_INPUT_HDMI_1"
        self.HDMI2 = "KEYCODE_TV_INPUT_HDMI_2"
        self.HDMI3 = "KEYCODE_TV_INPUT_HDMI_3"
        self.HDMI4 = "KEYCODE_TV_INPUT_HDMI_4"
        self.VIDEO = "KEYCODE_TV_INPUT_COMPOSITE_1"
